### ISSUE TITLE
Doesn't load open posts when returning back - Load More

### ISSUE THREAD

**Issue by thefubon** [putyourlightson/craft-sprig#96] opened 2021-02-02 12:26 UTC
### Describe the bug
Hello, Load More stopped working for me.
Cond I load posts in the Blog section, and then I go inside the news. And I press go back in the browser, All open pages with load through load more are reset.

https://github.com/putyourlightson/craft-sprig/issues/92#issue-797045365

### Screenshots

https://www.youtube.com/watch?v=h81CdJ2YObs&feature=youtu.be

### Versions
- Plugin version: 1.3.2
- Craft version: 3.6.2

**Comment by bencroker** [comment] 2021-02-02 12:28
Duplicate of https://github.com/putyourlightson/craft-sprig/issues/92.

**Closed as completed by bencroker** 2021-02-02 12:28 UTC
Labels: bug
