### ISSUE TITLE
Refresh meta tags when request was completed

### ISSUE THREAD

**Issue by billmn** [putyourlightson/craft-sprig#59] opened 2020-11-12 07:11 UTC
I have a twig partial (meta.twig) that contains all meta tags and is included in a base layout file. 

I would reload this partial to update meta tags when a Sprig component's request was completed. 

Ideas on how to accomplish that?

**Comment by bencroker** [comment] 2020-11-12 16:44
Why would you want to add meta tags to a Sprig component? Since the component would only change after an AJAX request, changing meta tags seems unnecessary.

**Comment by billmn** [comment] 2020-11-12 17:02
I have a product template that contains a `product` Sprig component.

```twig
{% extends "_layouts/main" %}

{% block main %}
    <div class="container">
        {{ sprig('_components/product', {
            _productId: product.id
        }) }}
        
        ...
    </div>
{% endblock %}
```

The product component contains informations about the product's variant:

```twig
<h1>{{ variant.title }}</h1>
<div>{{ variant.salePriceAsCurrency }}</div>

{% if product.variants|length > 1 %}
    <div>Choose a variant:</div>

    {% for item in product.variants %}
        <a
            href="{{ item.url }}"

            sprig
            s-vars="variant: {{ item.id }}"
            s-push-url="?variant={{ item.id }}"
        >
            {{ item.title }}
        </a>
    {% endfor %}
    </div>
{% endif %}
```

I would update, for example, the <title> tag with the Variant Title when the user switch from a variant to another.

**Comment by bencroker** [comment] 2020-11-12 17:07
You'll have to do that using JavaScript, for example:

```html
<script type="text/javascript">
    document.title = '{{ item.title }}';
</script>
```

**Comment by billmn** [comment] 2020-11-12 17:13
Yeah, you're right, I don't know why I got stubborn about wanting to update the meta partial.

Thank you and congrats for the awesome plugin!
Soon we will publish an ecommerce that uses Sprig intensively, love it! ♥️

**Comment by bencroker** [comment] 2020-11-12 17:20
Excellent, be sure to submit to https://github.com/putyourlightson/craft-sprig/blob/develop/INTHEWILD.md if possible.

**Comment by bencroker** [comment] 2020-11-23 09:58
As of version 1.1.0, Sprig uses [htmx 0.4.0](https://htmx.org/posts/2020-11-16-htmx-0.4.0-is-released/) which makes it possible to add a `title` tag in the component.

```html
<title>My new title</title>
```

**Comment by billmn** [comment] 2020-12-14 09:34
@bencroker I have used the `<title>` in a component but seems there is a problem.

This is the code I have used inside the component:
```twig
<title>Variant ID: {{ variant.id }}</title>

{# Product's Variants List #}
<div class="flex">
    {% for item in product.variants %}
        <a href="{{ item.url }}" sprig s-push-url="?variant={{ item.id }}" s-val:variant="{{ item.id }}">
            {{ item.id }}
        </a>
    {% endfor %}
</div>
```

The first load works correctly, and the component add the title tag with: "Variant ID: 94".

When I click on another variant, the title tag **was not created**.
If I click again on the same variant link (or on another variant link) it works. 

This is an example:

![Registrazione schermo 2020-12-14 alle 10 22 41](https://user-images.githubusercontent.com/779534/102064430-91f68200-3df7-11eb-8a55-c238cc444dfd.gif)

Thoughts?

**Comment by bencroker** [comment] 2020-12-14 13:15
Can you upload this to a public URL so I can inspect it in more detail?

**Comment by billmn** [comment] 2020-12-14 14:43
I have created a repo for you: https://github.com/billmn/sprig-test

Simply create at least 2 entries and you can see the problem.

**Comment by bencroker** [comment] 2020-12-14 14:48
Sorry for the confusion but a repo doesn't help me. I need to see this happening to help. Can you reproduce this behaviour in the Sprig playground and paste your code here?

**Comment by billmn** [comment] 2020-12-14 14:58
To see the problem you need that there isn't any <title> tag in the page, and is not possible in the admin panel.

If it can speed it up, I can send you the database dump

**Comment by bencroker** [comment] 2020-12-14 16:46
I'm not following, why would your initial page load not have a `<title>` tag? From your screenshare, it looks like there is an initial title of `Variant ID: 94`.

**Comment by billmn** [comment] 2020-12-14 17:07
The title "Variant ID: 94" is created by the Sprig Component and to accomplish that I need to not specify the title tag on the template that include this component.

But a missing title tag on the template that include the component seems to create the issue

**Comment by bencroker** [comment] 2020-12-14 18:44
Hmm, this sounds very edge case. If you can set up a live stripped-down example then I can take a look. This might be an issue with htmx and not Sprig.

**Comment by bencroker** [comment] 2020-12-15 16:08
Closing since this issue has been diverted from the original question. Please submit a bug report issue with an example if the issue persists.

**Closed as completed by bencroker** 2020-12-15 16:08 UTC
