### ISSUE TITLE
Submitted array values are merged with  default component variables

### ISSUE THREAD

**Issue by jiricerhan** [putyourlightson/craft-sprig#352] opened 2024-02-09 15:03 UTC
**Description**

When submitting array values through input `<input name="key[index]">`  it, after submitting, gets merged with values provied as default component variables when loading the template with `spirg` macro.

So insted of expeted two labels on first submit i get 4. The defaults and submitted.

The default array should be replaced with submitted values with the same index in my opinion. 

**Versions**

Sprig version 2.7.3
Craft version 4.5.10

**Steps to reproduce:**

1. Using this code

templates/index.twig
```twig
{{ sprig('test', {labels: ['a', 'b' ]}) }}
```
templates/test.twig
```twig
{{ dump(labels) }}
{% for label in labels %}
    <input sprig type="text" name="labels[{{ loop.index0 }}]" value="{{ label }}" />
{% endfor %}
```

2. Update any input
3. Click outside input to submit

**Screenshots**
![image](https://github.com/putyourlightson/craft-sprig/assets/67420262/6cc688e4-18f7-4821-be79-46c2a58b9c5e)

Thanks

**Comment by bencroker** [comment] 2024-02-09 15:19
Variables are merged recursively, making this the expected behaviour. So it’s a feature, not a bug. 

You may have your reasons for wanting a simple merge, but there are counter arguments too. Plus, changing this behaviour would be a breaking change.

**Comment by jiricerhan** [comment] 2024-02-09 15:43
Ok I get it now. Both defaults and post are merged with `array_merge_recursive(defaults, formValues)`. I would expect simple `array_merge`, this way I would get back what I have submitted.

The solution is to use asociative array with string indexes to make it owerride the default value insted of merging the two arrays togeather. Like so:

```twig
{{ sprig('test', {labels: {'a': 'a', 'b':'b' }}) }}
```

```sprig
{{ dump(labels) }}
{% for key, label in labels %}
    <input sprig type="text" name="labels[{{ key }}]" value="{{ label }}" />
{% endfor %}
```

This seems to be working fine. Thanaks a lot.

**Comment by bencroker** [comment] 2024-02-09 18:07
Precisely, and this way you can persist both default values an input values, if you want to.

**Closed as completed by bencroker** 2024-02-09 18:07 UTC
Labels: bug
