### ISSUE TITLE
Sprig with Smart Map

### ISSUE THREAD

**Issue by CreateSean** [putyourlightson/craft-sprig#78] opened 2021-01-06 20:56 UTC
### Question
Craft 3.5.17.1
Sprig 1.3.0
Smartmap 3.3.5

I'm attempting to sprigify a page with entry pagination and a google map powered by [smart maps](https://plugins.craftcms.com/smart-map).

Pagination and form filtering are working fine with the entries listed on the page. However when clicking through pagination or filtering the map goes blank.

![image](https://user-images.githubusercontent.com/6899490/103818780-23dc5e00-5037-11eb-992c-c723ea61dabd.png)

I've place the `sprig` attribute in the div wrapping wher ehte smartmap code goes but that doesn't seem to be helping.

see code:

```twig
{# Map #}
<div class="relative flex-100 md:mt-header mapped" sprig>

  {# more code here #}

  {# {% set locations = craft.entries.section('projects').all() %} #}
  {% set locations = entryQuery.all() %}
  {{ craft.smartMap.map(locations, options) }}

  {% include 'maps/_map-styles' %}

</div>
{# end map #}
```

Do I need to add the sprig attribute to the smartmap.map tag? There doesn't appear to be an option to add attributes https://plugins.doublesecretagency.com/smart-map/customizing-the-map-in-twig/#map-options

### Additional context
Add any other context or screenshots about the support request here.

**Comment by bencroker** [comment] 2021-01-06 22:07
My guess is that Smart Map outputs some JavaScript files when `craft.smartMap.map` is called. Given that this template is re-rendered and the result loaded over AJAX, you need to account for the fact that browsers will block scripts that exist in the returned value as a security precaution.

Instead, you'd need to find a way to re-instantiate Smart Map after re-rendering, for example:

```js
<script>
   htmx.on('htmx:afterSwap', function(event) {
       // Re-instantiate Smart Map
   });
</script>
```

Perhaps @lindseydiloreto can be of assistance?

**Comment by CreateSean** [comment] 2021-01-07 13:54
I tried this:

```javascript
<script>
   htmx.on('htmx:afterSwap', function(event) {
       smartMap.refreshMap('main-map1');
   });
</script>
```

but it didn't work. Will hit up Lindsey and when I get a solution update this thread for future reference.

**Comment by lindseydiloreto** [comment] 2021-01-12 00:45
Did a little experimenting with an upcoming beta, and it looks like everything is working smoothly! I chatted with @CreateSean  via DM, I think we've got everything working as intended.

Thanks @bencroker, feel free to close this thread! 🍺

**Comment by bencroker** [comment] 2021-01-12 08:41
Thank you @lindseydiloreto!

**Closed as completed by bencroker** 2021-01-12 08:41 UTC
Labels: question

**Comment by ConversioniaDev** [comment] 2021-02-11 16:56
> Did a little experimenting with an upcoming beta, and it looks like everything is working smoothly! I chatted with @CreateSean via DM, I think we've got everything working as intended.
> 
> Thanks @bencroker, feel free to close this thread! 🍺

What was the solution? I'm having the same issue.

**Comment by lindseydiloreto** [comment] 2021-02-11 17:43
@ConversioniaDev The solution relies on an upcoming beta version of Smart Map. If you'd like a copy of the beta, feel free to DM me on Discord (or email support@doublesecretagency.com).

Alternatively, you could just wait about 2 weeks for me to release it publicly. 😉

**Comment by lindseydiloreto** [comment] 2022-02-26 22:33
This thread is a bit old, but I think two important updates need to be mentioned...

 - Smart Map has been replaced by the [Google Maps plugin](https://www.doublesecretagency.com/blog/smart-map-is-dead-long-live-google-maps).
 - Integration between Sprig and Google Maps has now been [fully documented](https://plugins.doublesecretagency.com/google-maps/guides/sprig/).

For more info, ping [Double Secret Agency](https://www.doublesecretagency.com/contact). 👍
